# Permalinks
#
# Use of `absolute_permalinks` ensures post links from the index work properly.
permalink:           pretty
absolute_permalinks: true

# Setup
title:               My blog
tagline:             'A Jekyll theme'
description:         ''
url:                 https://daniel985.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Daniel Wang
  url:               https://daniel985.github.io
  email:             wangzhanoop@163.com

# Custom vars
version:             1.0.0

theme: jekyll-theme-time-machine