# Permalinks
permalink:          /blog/:year/:month/:day/:title/

# Setup
title:              Daniel's blog
baseurl:            'https://daniel985.github.io'

# About/contact
author:             Daniel Wang
url:                https://daniel985.github.io
email:              wangzhanoop@163.com

